# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: yarn

    - name: Test and Build  
    - run: yarn test
    - run: yarn build

    - name: Deploy
      uses: cultureweb/ftp-deploy-action@v1.2.1  
    with:
    ftp_host: ${{ secrets.HOST }}
    ftp_username: ${{ secrets.USERNAME }}
    ftp_password: ${{ secrets.PASSWORD }}
    local_source_dir: "build"
    dist_target_dir: "dev"
    delete: "true"
    exclude: "'^logs/' '^README.md'"


